// 
// Decompiled by Procyon v0.5.36
// 

package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.internal.b0;
import com.google.android.gms.common.api.w;
import com.google.android.gms.common.api.u;
import java.util.concurrent.TimeUnit;
import androidx.annotation.j0;
import com.google.android.gms.common.internal.x;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.n;
import com.google.android.gms.common.api.t;

public final class e2<R extends t> extends n<R>
{
    private final Status a;
    
    public e2(final Status a) {
        x.l(a, "Status must not be null");
        x.b(a.j3() ^ true, "Status must not be success");
        this.a = a;
    }
    
    @Override
    public final void c(@j0 final a a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @j0
    @Override
    public final R d() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @j0
    @Override
    public final R e(final long n, @j0 final TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public final void f() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public final boolean g() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public final void h(@j0 final u<? super R> u) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public final void i(@j0 final u<? super R> u, final long n, @j0 final TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @j0
    @b0
    @Override
    public final <S extends t> com.google.android.gms.common.api.x<S> j(@j0 final w<? super R, ? extends S> w) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @j0
    final Status k() {
        return this.a;
    }
}
